project_root: "/content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/mission6"

data:
  root: "/content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/mission6/data"
  train_dir: "/content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/mission6/data/train"
  val_dir: "/content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/mission6/data/val"
  test_dir: "/content/drive/Othercomputers/내 MacBook Air/Documents/ai_project/mission6/data/test"

exp_idx: 0

hparam:
  train:
    seed: 42
    batch_size: 128
    optimizer: Adam
    lr: 0.001
    epochs: 3

  resize:
    width: 224
    height: 224

  models:
    resnet50:
      type: resnet50
      pretrained: True
      num_classes: 10
      freeze_backbone: True

    efficientnet_b0:
      type: efficientnet_b0
      pretrained: True
      num_classes: 10
      freeze_backbone: False

    vit_base_patch16_244:
      type: vit_base_patch16_244
      pretrained: True
